### ISSUE TITLE
Both "LfEdit" and "LfSplit" spawn new vim instance

### ISSUE THREAD

**Issue by fedeztk** [thezeroalpha/vim-lf#3]
Vim 8.2, pop-up window works perfectly, but if I open a file a new instance of Vim is created.
I tried the lf built-in open and this customized:
```
cmd open ${{
    case $(file --mime-type $f -b) in
    text/*) $EDITOR $fx;;
    *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
    esac
}}
```
The built-in spawns a new window with the file, the customized spawns inside the popup window. 
Hope to find a solution.

**Comment by thezeroalpha** [comment]
@fedeztk did you manage to find a solution? I haven't run into this issue myself so I haven't responded yet, but I'd be interested if you were able to pinpoint or solve what was wrong.

**Comment by fedeztk** [comment]
I'm pretty sure that it was totally my fault, at that time I had lf not so well configured, now I use the plugin suggested in the lf repo, but I have to give this another shot. I will check if the size of the window is now fixed (when I tried it was "cut").
Thank you anyways, my bad.
